Repository BaSP-a2022/marta-a-trackgenix-app, pull requests merged in 2022-11, with the labels that each got.

#3 BaSP-TG-7: Employees list and delete
  src/Components/Employees/List/index.js
  src/Components/Employees/Modal/index.js
  src/Components/Employees/Modal/modal.module.css
  src/Components/Employees/employees.module.css
  src/Components/Employees/index.js
Labels: Ready to review

#1 BaSP-TG-1: Super admins list and delete
  package-lock.json
  public/assets/images/btn-add.svg
  public/assets/images/icon-close.svg
  public/assets/images/icon-delete.svg
  public/assets/images/icon-edit.svg
  src/Components/Layout/index.js
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/Form/index.js
  src/Components/SuperAdmins/List/index.js
  src/Components/SuperAdmins/List/list.module.css
  src/Components/SuperAdmins/ListItem/index.js
  src/Components/SuperAdmins/ListItem/listItem.module.css
  src/Components/SuperAdmins/Modal/index.js
  src/Components/SuperAdmins/Modal/modal.module.css
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
Labels: Ready for QA

#6 BsSP-TG-9: Employees create and edit
  src/Components/Employees/Form/form.module.css
  src/Components/Employees/Form/index.js
  src/Components/Employees/List/index.js
  src/Components/Employees/Modal/index.js
  src/Components/Employees/index.js
  src/Components/Layout/index.js
Labels: Ready for QA

#5 BsSP-TG-10: timesheet list / delete / add / edit
  package-lock.json
  src/Components/Layout/index.js
  src/Components/TimeSheets/List/List.css
  src/Components/TimeSheets/List/List.jsx
  src/Components/TimeSheets/ListItem/ListItem.css
  src/Components/TimeSheets/ListItem/ListItem.jsx
  src/Components/TimeSheets/Modal/Modal.css
  src/Components/TimeSheets/Modal/Modal.jsx
  src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.css
  src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.jsx
  src/Components/TimeSheets/index.js
  src/Components/TimeSheets/time-sheets.module.css
Labels: Ready for QA

#9 BaSP TG-22: Shared Button Component
  public/assets/images/pen-to-square-solid.svg
  public/assets/images/trash-solid.svg
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Button/index.js
Labels: Ready for deploy

#2 BaSP-TG-5 & 8: Projects page list, delete, add and edit
  public/assets/images/delete.svg
  public/assets/images/edit.svg
  src/Components/Layout/index.js
  src/Components/Projects/Form/form.js
  src/Components/Projects/Form/form.module.css
  src/Components/Projects/Modal/modal.js
  src/Components/Projects/Modal/modal.module.css
  src/Components/Projects/index.js
  src/Components/Projects/projects.module.css
Labels: Ready for QA

#13 BaSP-TG-21: React router implementation
  package-lock.json
  package.json
  src/Components/Footer/index.js
  src/Components/Header/index.js
  src/Components/Layout/index.js
  src/Components/Layout/routes.js
  src/Components/TimeSheets/List/List.js
  src/Components/TimeSheets/List/List.jsx
  src/Components/TimeSheets/List/List.module.css
  src/Components/TimeSheets/ListItem/ListItem.js
  src/Components/TimeSheets/ListItem/ListItem.module.css
  src/Components/TimeSheets/Modal/Modal.js
  src/Components/TimeSheets/Modal/Modal.jsx
  src/Components/TimeSheets/Modal/Modal.module.css
  src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.js
  src/Components/TimeSheets/TimeSheetsForm/timeSheetsForm.module.css
Labels: Ready for QA

#10 BaSP TG-26: Shared Form Component
  src/Components/Shared/Form/form.module.css
  src/Components/Shared/Form/index.js
  src/index.css
Labels: Ready for deploy

#12 BaSP-TG-27: create input and select component
  src/Components/Shared/Input/index.js
  src/Components/Shared/Input/input.module.css
Labels: Ready for deploy

#22 BaSP TG-42: Components hotfix
  public/assets/images/angle-left-solid.svg
  public/assets/images/angle-right-solid.svg
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Button/index.js
  src/Components/Shared/Form/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Row/index.js
  src/Components/Shared/Row/row.module.css
  src/Components/Shared/Table/Row/index.js
  src/Components/Shared/Table/Row/row.module.css
  src/Components/Shared/Table/index.js
  src/Components/Shared/Table/table.module.css
Labels: Ready to review

#20 BaSP-TG-27: Create input and select component
  src/Components/Shared/Input/index.js
Labels: Ready to review

#17 BaSP TG-31: Timesheet components implementation
  src/Components/Layout/routes.js
  src/Components/Shared/Input/index.js
  src/Components/TimeSheets/List/List.js
  src/Components/TimeSheets/List/List.module.css
  src/Components/TimeSheets/ListItem/ListItem.js
  src/Components/TimeSheets/ListItem/ListItem.module.css
  src/Components/TimeSheets/Modal/Modal.js
  src/Components/TimeSheets/Modal/Modal.module.css
  src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.js
  src/Components/TimeSheets/TimeSheetsForm/index.js
  src/Components/TimeSheets/TimeSheetsForm/timeSheetsForm.module.css
  src/Components/TimeSheets/TimeSheetsTable/List.module.css
  src/Components/TimeSheets/TimeSheetsTable/index.js
  src/Components/TimeSheets/index.js
  src/Components/TimeSheets/time-sheets.module.css
Labels: Ready for QA

#21 BaSP TG-33: Task components implementation
  src/Components/Layout/routes.js
  src/Components/Tasks/TasksForm/index.js
  src/Components/Tasks/TasksForm/tasksForm.module.css
  src/Components/Tasks/index.js
  src/Components/Tasks/tasks.module.css
Labels: Ready for deploy

#18 BaSP-32: Super-Admins shared components implementation
  src/Components/Shared/Modal/modal.module.css
  src/Components/Shared/Table/table.module.css
  src/Components/SuperAdmins/Form/index.js
  src/Components/SuperAdmins/List/index.js
  src/Components/SuperAdmins/List/list.module.css
  src/Components/SuperAdmins/ListItem/index.js
  src/Components/SuperAdmins/ListItem/listItem.module.css
  src/Components/SuperAdmins/Modal/index.js
  src/Components/SuperAdmins/Modal/modal.module.css
  src/Components/SuperAdmins/ModalAlert/index.js
  src/Components/SuperAdmins/ModalAlert/modalAlert.module.css
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
Labels: Ready for QA

#19 BaSP-TG-30: Admins implement shared components
  src/Components/Admins/Form/form.module.css
  src/Components/Admins/Form/index.js
  src/Components/Admins/admins.module.css
  src/Components/Admins/form.js
  src/Components/Admins/index.js
  src/Components/Admins/modal.js
  src/Components/Admins/modal.module.css
  src/Components/Layout/routes.js
  src/Components/Shared/Modal/modal.module.css
Labels: Ready for deploy

#25 BaSP-TG-41: Redux Setup
  package-lock.json
  package.json
  src/index.js
  src/redux/Admins/actions.js
  src/redux/Admins/reducer.js
  src/redux/Admins/thunks.js
  src/redux/Admins/types.js
  src/redux/Employees/actions.js
  src/redux/Employees/reducer.js
  src/redux/Employees/thunks.js
  src/redux/Employees/types.js
  src/redux/Projects/actions.js
  src/redux/Projects/reducer.js
  src/redux/Projects/thunks.js
  src/redux/Projects/types.js
  src/redux/SuperAdmins/actions.js
  src/redux/SuperAdmins/reducer.js
  src/redux/SuperAdmins/thunks.js
  src/redux/SuperAdmins/types.js
  src/redux/Tasks/actions.js
  src/redux/Tasks/reducer.js
  src/redux/Tasks/thunks.js
  src/redux/Tasks/types.js
  src/redux/TimeSheets/actions.js
  src/redux/TimeSheets/reducer.js
  src/redux/TimeSheets/thunks.js
  src/redux/TimeSheets/types.js
  src/redux/rootReducer.js
  src/redux/store.js
Labels: Resolve comments

#28 BaSP TG-58: Shared components hotfix
  src/Components/Shared/Form/form.module.css
  src/Components/Shared/Form/index.js
  src/Components/Shared/Input/input.module.css
  src/Components/Shared/Modal/index.js
  src/Components/Shared/Modal/modal.module.css
  src/Components/Shared/Table/Row/index.js
  src/Components/Shared/Table/Row/row.module.css
  src/Components/Shared/Table/index.js
  src/Components/Shared/Table/table.module.css
Labels: Ready to review

#26 BaSP-TG-43: Admins redux GET
  src/Components/Admins/index.js
  src/redux/Admins/reducer.js
  src/redux/Admins/thunks.js
Labels: Ready for QA

#27 BaSP-TG-47: SuperAdmins Redux GET
  src/Components/SuperAdmins/index.js
  src/redux/SuperAdmins/reducer.js
  src/redux/SuperAdmins/thunks.js
Labels: Ready for QA

#29 BaSP TG-52: Projects redux GET
  src/Components/Projects/Form/form.js
  src/Components/Projects/Form/form.module.css
  src/Components/Projects/index.js
  src/Components/Projects/projects.module.css
  src/Components/Shared/Input/input.module.css
  src/Components/Shared/Table/Row/index.js
  src/Components/Shared/Table/Row/row.module.css
  src/Components/Shared/Table/table.module.css
  src/redux/Employees/reducer.js
  src/redux/Employees/thunks.js
  src/redux/Projects/reducer.js
  src/redux/Projects/thunks.js
Labels: Ready for deploy

#34 BaSP TG-46: Employees redux create update delete
  src/Components/Employees/Form/index.js
  src/Components/Employees/index.js
  src/redux/Employees/actions.js
  src/redux/Employees/reducer.js
  src/redux/Employees/thunks.js
  src/redux/Employees/types.js
Labels: Ready for deploy

#31 BaSP-TG-48: redux create update & delete super admin
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/Form/index.js
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
  src/redux/SuperAdmins/actions.js
  src/redux/SuperAdmins/reducer.js
  src/redux/SuperAdmins/thunks.js
  src/redux/SuperAdmins/types.js
Labels: Ready for deploy

#35 BaSP-TG-53: Projects Redux POST, PUT and DELETE
  src/Components/Projects/Form/form.js
  src/Components/Projects/index.js
  src/redux/Projects/actions.js
  src/redux/Projects/reducer.js
  src/redux/Projects/thunks.js
  src/redux/Projects/types.js
Labels: Ready for deploy

#37 BaSP-TG-61: Loader and error shared component
  public/assets/images/error.svg
  src/Components/Shared/Error/error.module.css
  src/Components/Shared/Error/index.js
  src/Components/Shared/Loader/index.js
  src/Components/Shared/Loader/loading.module.css
Labels: Ready to review

#36 BaSP-TG-50: Timesheet redux - GET
  src/Components/TimeSheets/TimeSheetsForm/index.js
  src/Components/TimeSheets/TimeSheetsTable/List.module.css
  src/Components/TimeSheets/TimeSheetsTable/index.js
  src/redux/TimeSheets/reducer.js
  src/redux/TimeSheets/thunks.js
Labels: Ready for deploy

#39 BaSP-TG-55: Tasks Redux POST, PUT and DELETE
  src/Components/Tasks/TasksForm/index.js
  src/Components/Tasks/index.js
  src/redux/Tasks/actions.js
  src/redux/Tasks/reducer.js
  src/redux/Tasks/thunks.js
  src/redux/Tasks/types.js
Labels: Ready for deploy

#32 BaSP-TG-44: Redux Admins delete, create, edit.
  src/Components/Admins/Form/index.js
  src/Components/Admins/admins.module.css
  src/Components/Admins/index.js
  src/redux/Admins/actions.js
  src/redux/Admins/reducer.js
  src/redux/Admins/thunks.js
  src/redux/Admins/types.js
Labels: Ready for deploy

#41 BaSP-TG-63: setup libraries
  package-lock.json
  package.json
Labels: Ready for deploy

#40 BaSP-TG-64: Absolute routes
  jsconfig.json
  src/Components/Projects/Form/form.js
  src/Components/Projects/index.js
Labels: Ready for deploy

#42 BaSP-TG-65: Employee layout
  public/assets/images/angle-down-solid.svg
  public/assets/images/angle-up-solid.svg
  public/assets/images/edit.png
  public/assets/images/facebook.svg
  public/assets/images/instagram.svg
  public/assets/images/trash.png
  public/assets/images/twitter.svg
  src/Components/Employee/Home/home.module.css
  src/Components/Employee/Home/index.js
  src/Components/Employee/Profile/index.js
  src/Components/Employee/Profile/profile.module.css
  src/Components/Employee/Projects/index.js
  src/Components/Employee/Projects/projects.module.css
  src/Components/Employee/Timesheets/index.js
  src/Components/Employee/Timesheets/timesheets.module.css
  src/Components/Footer/footer.module.css
  src/Components/Footer/index.js
  src/Components/Header/header.module.css
  src/Components/Header/index.js
  src/Components/Layout/routes.js
Labels: Ready for deploy

#44 BaSP-TG-66: Lazy loading
  src/Components/Footer/footer.module.css
  src/Components/Layout/index.js
  src/Components/Layout/routes.js
  src/Components/Projects/Form/index.js
Labels: Ready to review

#43 BaSP-TG-73: update shared inputs component
  src/Components/Shared/Error/error.module.css
  src/Components/Shared/Error/index.js
  src/Components/Shared/Form/form.module.css
  src/Components/Shared/Input/index.js
  src/Components/Shared/Input/input.module.css
Labels: Ready to review

#45 BaSP-TG-69: Employees useForm
  src/Components/Employees/Form/index.js
  src/Components/Employees/Form/validations.js
  src/Components/Employees/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Input/input.module.css
Labels: Ready for deploy

#50 BaSP-TG-72: Form Projects
  src/Components/Projects/Form/form.module.css
  src/Components/Projects/Form/index.js
  src/Components/Projects/Form/validations.js
  src/Components/Projects/index.js
  src/Components/Shared/Input/index.js
  src/redux/Projects/thunks.js
Labels: Ready for deploy

#47 BaSP TG-67: Admin react hook form
  src/Components/Admins/Form/index.js
  src/Components/Admins/Form/validations.js
  src/Components/Admins/index.js
  src/Components/Shared/Input/index.js
Labels: Ready for deploy

#51 BaSP-TG-76: EMPLOYEE-Profile Page
  src/Components/Employee/Profile/index.js
  src/Components/Employee/Profile/validations.js
Labels: Ready for deploy

#53 BaSP TG-74: Employees projects page
  src/Components/Employee/Projects/index.js
  src/Components/Employee/Projects/projects.module.css
Labels: Ready for deploy

#54 BaSP-TG-78: Styles fixes and dark mode
  public/assets/images/angle-down-solid.svg
  public/assets/images/angle-left-solid.svg
  public/assets/images/angle-right-solid.svg
  public/assets/images/angle-up-solid.svg
  public/assets/images/btn-add.svg
  public/assets/images/close-cross.svg
  public/assets/images/delete.svg
  public/assets/images/edit.svg
  public/assets/images/error.svg
  public/assets/images/icon-close.svg
  public/assets/images/icon-delete.svg
  public/assets/images/icon-edit.svg
  public/assets/images/pen-to-square-solid.svg
  public/assets/images/trash-solid.svg
  public/index.html
  src/Components/Admins/admins.module.css
  src/Components/Admins/index.js
  src/Components/Employee/Profile/index.js
  src/Components/Footer/footer.module.css
  src/Components/Header/header.module.css
  src/Components/Projects/Form/form.module.css
  src/Components/Projects/Form/index.js
  src/Components/Projects/index.js
  src/Components/Projects/projects.module.css
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Button/index.js
  src/Components/Shared/Error/error.module.css
  src/Components/Shared/Form/form.module.css
  src/Components/Shared/Input/index.js
  src/Components/Shared/Input/input.module.css
  src/Components/Shared/Modal/index.js
  src/Components/Shared/Modal/modal.module.css
  src/Components/Shared/Table/Row/row.module.css
  src/Components/Shared/Table/table.module.css
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/index.js
  src/Components/Tasks/index.js
  src/Components/TimeSheets/TimeSheetsTable/List.module.css
  src/Components/TimeSheets/TimeSheetsTable/index.js
  src/index.css
Labels: Ready for deploy

#55 BaSP-TG-89: Set up firebase
  package-lock.json
  package.json
  src/Components/Admins/Form/index.js
  src/Components/Header/header.module.css
  src/Components/Layout/routes.js
  src/Components/Shared/Input/input.module.css
  src/helpers/firebase/index.js
  src/redux/Auth/actions.js
  src/redux/Auth/reducer.js
  src/redux/Auth/thunks.js
  src/redux/Auth/types.js
Labels: Ready for deploy

#56 BaSP TG-98: Redux auth
  src/redux/Auth/actions.js
  src/redux/Auth/reducer.js
  src/redux/Auth/thunks.js
  src/redux/Auth/types.js
Labels: Ready to review

#57 BaSP-TG-105: Hot fixes errors when displaying the data
  src/Components/Admins/index.js
  src/Components/Employee/Timesheets/index.js
  src/Components/Employees/index.js
  src/Components/Projects/Form/index.js
  src/Components/Projects/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Table/index.js
  src/Components/SuperAdmins/Form/index.js
  src/Components/Tasks/TasksForm/index.js
  src/Components/Tasks/index.js
  src/Components/TimeSheets/TimeSheetsForm/index.js
  src/Components/TimeSheets/TimeSheetsTable/index.js
Labels: Ready to review
