Repository BaSP-a2022/marta-a-trackgenix-app, pull requests merged in 2022-12, with the labels that each got.

#58 BaSP-TG-97: update user routes
  src/Components/Entities/Employee/Home/home.module.css
  src/Components/Entities/Employee/Home/index.js
  src/Components/Entities/Employee/Profile/index.js
  src/Components/Entities/Employee/Profile/profile.module.css
  src/Components/Entities/Employee/Profile/validations.js
  src/Components/Entities/Employee/Projects/index.js
  src/Components/Entities/Employee/Projects/projects.module.css
  src/Components/Entities/Employee/Timesheets/Form/form.module.css
  src/Components/Entities/Employee/Timesheets/Form/index.js
  src/Components/Entities/Employee/Timesheets/Form/validations.js
  src/Components/Entities/Employee/Timesheets/index.js
  src/Components/Entities/Employee/Timesheets/timesheets.module.css
  src/Components/Layout/index.js
  src/Components/SuperAdmins/index.js
  src/Components/SuperAdmins/super-admins.module.css
  src/Components/TimeSheets/TimeSheetsTable/List.module.css
  src/Components/TimeSheets/TimeSheetsTable/index.js
  src/routes/PrivateRoute.js
  src/routes/index.js
Labels: Ready for deploy

#64 BaSP-TG-110: Add search feature to shared table component
  src/Components/Shared/Input/index.js
  src/Components/Shared/Input/input.module.css
  src/Components/Shared/Input/magnifying-glass-solid-dark.svg
  src/Components/Shared/Input/magnifying-glass-solid-light.svg
  src/Components/Shared/Table/index.js
  src/Components/Shared/Table/table.module.css
Labels: Ready to review

#65 BaSP-TG-111: hotfix employee routs
  src/Components/Auth/Login/index.js
  src/Components/Entities/Employee/Home/index.js
  src/Components/Entities/Employee/Profile/index.js
  src/Components/Entities/Employee/Projects/index.js
  src/Components/Entities/Employee/Timesheets/index.js
  src/Components/Footer/index.js
  src/Components/Header/index.js
  src/Components/Shared/Form/index.js
  src/helpers/firebase/index.js
  src/redux/Auth/actions.js
  src/redux/Auth/reducer.js
  src/redux/Auth/thunks.js
  src/redux/Auth/types.js
  src/redux/Projects/thunks.js
  src/redux/TimeSheets/thunks.js
  src/routes/PrivateRoute.js
  src/routes/index.js
Labels: Ready to review

#63 BaSP-TG-107: Filter employees
  src/Components/Employees/index.js
  src/Components/Entities/Employee/Profile/index.js
  src/Components/Entities/Employee/Projects/index.js
  src/Components/Projects/Form/index.js
  src/Components/Projects/Form/validations.js
  src/Components/Projects/index.js
  src/Components/Shared/Input/index.js
  src/redux/Employees/thunks.js
  src/redux/Projects/thunks.js
Labels: Ready to review

#68 BaSP-TG-114: Show employee timesheets
  src/Components/Entities/Employee/Profile/index.js
  src/Components/Entities/Employee/Profile/profile.module.css
  src/Components/Entities/Employee/Profile/validations.js
  src/Components/Entities/Employee/Profile/validationsPass.js
  src/Components/Entities/Employee/Timesheets/Form/index.js
  src/Components/Entities/Employee/Timesheets/index.js
  src/Components/Shared/Form/form.module.css
  src/Components/Shared/Form/index.js
  src/Components/Shared/Input/index.js
  src/redux/Employees/thunks.js
  src/redux/TimeSheets/thunks.js
Labels: Ready for QA

#70 BaSP TG-108: Home Component
  public/assets/images/home.png
  src/Components/Admins/index.js
  src/Components/Auth/Login/index.js
  src/Components/Employees/index.js
  src/Components/Entities/Employee/Home/index.js
  src/Components/Entities/Employee/Profile/profile.module.css
  src/Components/Entities/Employee/Projects/index.js
  src/Components/Entities/Employee/Timesheets/index.js
  src/Components/Header/header.module.css
  src/Components/Header/index.js
  src/Components/Home/index.js
  src/Components/Landing/index.js
  src/Components/Landing/landing.module.css
  src/Components/Projects/index.js
  src/Components/Shared/Button/button.module.css
  src/Components/Shared/Home/home.module.css
  src/Components/Shared/Home/index.js
  src/Components/SuperAdmins/Form/form.module.css
  src/Components/SuperAdmins/index.js
  src/Components/Tasks/index.js
  src/Components/TimeSheets/TimeSheetsTable/index.js
  src/index.css
  src/redux/Auth/thunks.js
  src/routes/index.js
Labels: Ready for deploy

#72 BaSP TG-122: fix bug form
  src/Components/Entities/Admin/Employees/Form/index.js
  src/Components/Entities/Admin/Employees/Form/validations.js
  src/Components/Entities/Admin/Employees/index.js
  src/Components/Entities/Admin/Profile/index.js
  src/Components/Entities/Admin/Projects/Form/index.js
  src/Components/Entities/Admin/Projects/index.js
  src/Components/Entities/Admin/Tasks/TasksForm/validations.js
  src/Components/Entities/Employee/Profile/index.js
  src/Components/Entities/SuperAdmin/Profile/index.js
  src/Components/Shared/Modal/index.js
  src/redux/Projects/thunks.js
Labels: Ready to review
